# Add QC information
The purpose of this notebook is to take an existing phenotype file and add QC information

In [38]:
import os
import re
import pandas as pd

In [141]:
# Paths
pheno_path = '/data1/abide/Pheno/pheno.csv'
qc_motion_path = '/data1/abide/Pheno/motion_all.csv'
merged_path = '/data1/abide/Pheno/merged_pheno.csv'

In [133]:
pheno = pd.read_csv(pheno_path)
qc_motion = pd.read_csv(qc_motion_path)
# Rename header of QC file
colnames = qc_motion.columns.values
colnames[0] = 'SUB_ID'
qc_motion.columns = colnames
# Change subject IDs
qc_names = [int(re.search('(?<=X)[0-9]*',row['SUB_ID']).group()) for index, row in qc_motion.iterrows()]
qc_motion['SUB_ID'] = qc_names

In [134]:
qc_motion.head()

   SUB_ID  frames_scrubbed   frames_OK        FD   FD_scrubbed
0   51328                 7         113  0.149900     0.134066
1   51332                17         103  0.151046     0.118284
2   51333                19         101  0.223314     0.195800
3   51334                22          98  0.241574     0.174444
4   51335                 0         120  0.135168     0.135168

In [8]:
pheno.head()

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
0,CALTECH,51456,1,4,55.4,1,R,NaN,126,118,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
1,CALTECH,51457,1,4,22.9,1,Ambi,NaN,107,119,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
2,CALTECH,51458,1,1,39.2,1,R,NaN,93,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
3,CALTECH,51459,1,1,22.8,1,R,NaN,106,94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
4,CALTECH,51460,1,1,34.6,2,Ambi,NaN,133,135,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN

In [135]:
combined_pheno = pheno.merge(qc_motion, on='SUB_ID')

In [150]:
combined_pheno.head()

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI,frames_scrubbed,frames_OK,FD,FD_scrubbed
0,CALTECH,51456,1,4,55.4,1,R,NaN,126,118,...,NaN,NaN,NaN,2,NaN,NaN,95,55,0.434593,0.328121
1,CALTECH,51457,1,4,22.9,1,Ambi,NaN,107,119,...,NaN,NaN,NaN,2,NaN,NaN,16,134,0.207160,0.170893
2,CALTECH,51458,1,1,39.2,1,R,NaN,93,80,...,NaN,NaN,NaN,2,NaN,NaN,18,132,0.322805,0.288872
3,CALTECH,51459,1,1,22.8,1,R,NaN,106,94,...,NaN,NaN,NaN,2,NaN,NaN,0,150,0.152963,0.152963
4,CALTECH,51460,1,1,34.6,2,Ambi,NaN,133,135,...,NaN,NaN,NaN,2,NaN,NaN,0,150,0.207277,0.207277

In [151]:
out_pheno = combined_pheno.loc[combined_pheno.duplicated('SUB_ID').values==False]

In [152]:
out_pheno.to_csv(merged_path, index=False)

In [153]:
test = pd.read_csv(merged_path)

In [154]:
test.head()

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI,frames_scrubbed,frames_OK,FD,FD_scrubbed
0,CALTECH,51456,1,4,55.4,1,R,NaN,126,118,...,NaN,NaN,NaN,2,NaN,NaN,95,55,0.434593,0.328121
1,CALTECH,51457,1,4,22.9,1,Ambi,NaN,107,119,...,NaN,NaN,NaN,2,NaN,NaN,16,134,0.207160,0.170893
2,CALTECH,51458,1,1,39.2,1,R,NaN,93,80,...,NaN,NaN,NaN,2,NaN,NaN,18,132,0.322805,0.288872
3,CALTECH,51459,1,1,22.8,1,R,NaN,106,94,...,NaN,NaN,NaN,2,NaN,NaN,0,150,0.152963,0.152963
4,CALTECH,51460,1,1,34.6,2,Ambi,NaN,133,135,...,NaN,NaN,NaN,2,NaN,NaN,0,150,0.207277,0.207277

In [155]:
test.shape

(879, 78)